# Generated by Django 5.2.8 on 2025-11-27 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_cabang', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('kontak', models.CharField(max_length=100)),
                ('manager', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inventori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kategori', models.CharField(choices=[('obat', 'Obat'), ('perlengkapan', 'Perlengkapan')], max_length=50)),
                ('stok', models.IntegerField(default=0)),
                ('harga', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_supplier', models.CharField(max_length=100)),
                ('kategori', models.CharField(choices=[('obat', 'Obat'), ('perlengkapan', 'Perlengkapan')], max_length=50)),
                ('kontak', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BarangMasuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('inventori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistik.inventori')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistik.supplier')),
            ],
        ),
    ]
