# Generated by Django 5.2.8 on 2025-11-27 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('konsultasi', '0001_initial'),
        ('pasien', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwalbooking',
            name='pasien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_bookings', to='pasien.pasien'),
        ),
        migrations.AddField(
            model_name='jadwalbooking',
            name='jadwal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='konsultasi.jadwalkonselor'),
        ),
        migrations.AddField(
            model_name='jadwalkonselor',
            name='konselor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='konsultasi.konselor'),
        ),
        migrations.AddField(
            model_name='jadwalbooking',
            name='konselor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='konsultasi.konselor'),
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pembayaran', to='konsultasi.jadwalbooking'),
        ),
        migrations.AddField(
            model_name='pembayaran',
            name='pasien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasien.pasien'),
        ),
    ]
