# Generated by Django 5.2.8 on 2025-11-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konsultasi', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jadwalkonselor',
            name='tanggal',
        ),
        migrations.AddField(
            model_name='jadwalkonselor',
            name='hari',
            field=models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu'), ('Minggu', 'Minggu')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
