# Generated by Django 6.0 on 2025-12-18 09:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konsultasi', '0003_remove_jadwalkonselor_tanggal_jadwalkonselor_hari'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwalbooking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jadwalbooking',
            name='tanggal_sesi',
            field=models.DateField(),
        ),
    ]
