# Generated by Django 5.2.8 on 2025-11-27 15:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('konsultasi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('umur', models.PositiveIntegerField(blank=True, null=True)),
                ('jenis_kelamin', models.CharField(blank=True, max_length=20)),
                ('kontak', models.CharField(blank=True, max_length=50)),
                ('alamat', models.TextField(blank=True)),
                ('tingkat_gangguan', models.CharField(blank=True, choices=[('ringan', 'Ringan'), ('sedang', 'Sedang'), ('berat', 'Berat')], max_length=10, null=True)),
                ('sudah_isi_kuesioner', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pasien_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Kuesioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(default=django.utils.timezone.now)),
                ('q1', models.IntegerField(default=1)),
                ('q2', models.IntegerField(default=1)),
                ('q3', models.IntegerField(default=1)),
                ('q4', models.IntegerField(default=1)),
                ('q5', models.IntegerField(default=1)),
                ('skor_total', models.IntegerField(default=0)),
                ('hasil', models.CharField(blank=True, max_length=10)),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kuesioner', to='pasien.pasien')),
            ],
            options={
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jam_mulai', models.TimeField()),
                ('durasi_menit', models.PositiveIntegerField(default=60)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('done', 'Done')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('konselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='konsultasi.konselor')),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='pasien.pasien')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiwayatKonsultasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(default=django.utils.timezone.now)),
                ('konselor_nama', models.CharField(blank=True, max_length=200)),
                ('ringkasan', models.TextField(blank=True)),
                ('jenis_sesi', models.CharField(blank=True, max_length=50)),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat', to='pasien.pasien')),
            ],
            options={
                'ordering': ['-tanggal'],
            },
        ),
    ]
