# Generated by Django 5.2.8 on 2025-11-27 15:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('konsultasi', '0002_initial'),
        ('logistik', '0001_initial'),
        ('pasien', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(default=django.utils.timezone.now)),
                ('catatan', models.TextField(blank=True)),
                ('konselor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='konsultasi.konselor')),
                ('konsultasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resep', to='konsultasi.jadwalbooking')),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resep', to='pasien.pasien')),
            ],
            options={
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='ObatOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_order', models.DateTimeField(default=django.utils.timezone.now)),
                ('metode', models.CharField(choices=[('ambil', 'Ambil di Klinik'), ('antar', 'Antar')], default='ambil', max_length=10)),
                ('alamat_pengiriman', models.TextField(blank=True)),
                ('jasa_pengiriman', models.CharField(blank=True, max_length=200)),
                ('biaya_kurir', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_obat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('diproses', 'Diproses'), ('dikirim', 'Dikirim'), ('selesai', 'Selesai'), ('batal', 'Batal')], default='pending', max_length=20)),
                ('pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pasien.pasien')),
                ('resep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='obat.resep')),
            ],
        ),
        migrations.CreateModel(
            name='ResepItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_obat', models.CharField(max_length=255)),
                ('dosis', models.CharField(blank=True, max_length=100)),
                ('jumlah', models.PositiveIntegerField(default=1)),
                ('harga_satuan', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('inventori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistik.inventori')),
                ('resep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='obat.resep')),
            ],
        ),
    ]
